name: Daily News Summary

on:
  schedule:
    # Runs at 7 AM UTC every day (adjust timezone as needed)
    # Use https://crontab.guru to customize the schedule
    - cron: '0 7 * * *'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  generate-news:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Needed to commit files
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create output directory
        run: mkdir -p output
      
      - name: Generate news summary
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          python generate_news.py
      
      - name: Commit and push changes
        run: |
          git config user.name "News Agent Bot"
          git config user.email "actions@github.com"
          git add output/*.html
          git commit -m "📰 Daily news summary - $(date +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
          git push
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-summary-${{ github.run_number }}
          path: output/*.html
          retention-days: 30
